[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NEXT_PUBLIC_BASE_URL = "https://intern-api.fly.dev"
  NEXT_PUBLIC_SITE_URL = "https://mcintern.netlify.app"
  NEXT_PUBLIC_SUPABASE_URL = "https://dnrtnzpehfifeyffayqo.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

[[plugins]]
  package = "@netlify/plugin-nextjs"
