// CORS Proxy URL
export const CORS_PROXY_URL = '/api/cors-proxy';

// Raw materials data
export const rawMaterials = [
  {
    id: 1,
    name: "Organic Strawberries",
    category: "Fruits",
    currentStock: 45,
    unit: "lbs",
    minStock: 20,
    maxStock: 100,
    costPerUnit: 4.5,
    lastOrdered: "2024-01-05",
    status: "In Stock",
    vendors: [
      { id: 1, name: "Fresh Farm Co.", price: 4.5, rating: 4.8, deliveryTime: "2-3 days" },
      { id: 2, name: "Organic Valley Suppliers", price: 4.75, rating: 4.6, deliveryTime: "1-2 days" },
      { id: 3, name: "Green Harvest Ltd.", price: 4.25, rating: 4.9, deliveryTime: "3-4 days" },
    ],
  },
  {
    id: 2,
    name: "Frozen Mango Chunks",
    category: "Fruits",
    currentStock: 12,
    unit: "lbs",
    minStock: 15,
    maxStock: 80,
    costPerUnit: 3.25,
    lastOrdered: "2024-01-03",
    status: "Low Stock",
    vendors: [
      { id: 1, name: "Tropical Fruits Inc.", price: 3.25, rating: 4.7, deliveryTime: "2-3 days" },
      { id: 2, name: "Exotic Imports", price: 3.5, rating: 4.5, deliveryTime: "1-2 days" },
    ],
  },
  {
    id: 3,
    name: "Greek Yogurt",
    category: "Dairy",
    currentStock: 28,
    unit: "containers",
    minStock: 25,
    maxStock: 60,
    costPerUnit: 2.8,
    lastOrdered: "2024-01-06",
    status: "In Stock",
    vendors: [
      { id: 1, name: "Dairy Fresh Co.", price: 2.8, rating: 4.9, deliveryTime: "1 day" },
      { id: 2, name: "Mountain View Dairy", price: 2.95, rating: 4.7, deliveryTime: "2 days" },
    ],
  },
  {
    id: 4,
    name: "Organic Spinach",
    category: "Vegetables",
    currentStock: 8,
    unit: "lbs",
    minStock: 10,
    maxStock: 40,
    costPerUnit: 3.75,
    lastOrdered: "2024-01-02",
    status: "Low Stock",
    vendors: [
      { id: 1, name: "Green Leaf Farms", price: 3.75, rating: 4.8, deliveryTime: "1-2 days" },
      { id: 2, name: "Organic Valley Suppliers", price: 3.9, rating: 4.6, deliveryTime: "2-3 days" },
    ],
  },
  {
    id: 5,
    name: "Chia Seeds",
    category: "Seeds & Nuts",
    currentStock: 22,
    unit: "lbs",
    minStock: 15,
    maxStock: 50,
    costPerUnit: 8.5,
    lastOrdered: "2024-01-04",
    status: "In Stock",
    vendors: [
      { id: 1, name: "Superfood Suppliers", price: 8.5, rating: 4.9, deliveryTime: "2-3 days" },
      { id: 2, name: "Health Foods Direct", price: 8.75, rating: 4.7, deliveryTime: "1-2 days" },
    ],
  },
  {
    id: 6,
    name: "Coconut Milk",
    category: "Dairy Alternatives",
    currentStock: 35,
    unit: "cans",
    minStock: 30,
    maxStock: 80,
    costPerUnit: 1.95,
    lastOrdered: "2024-01-05",
    status: "In Stock",
    vendors: [
      { id: 1, name: "Tropical Imports", price: 1.95, rating: 4.6, deliveryTime: "2-3 days" },
      { id: 2, name: "Coconut Co.", price: 2.1, rating: 4.8, deliveryTime: "1-2 days" },
    ],
  },
  {
    id: 7,
    name: "Protein Powder (Vanilla)",
    category: "Supplements",
    currentStock: 5,
    unit: "containers",
    minStock: 8,
    maxStock: 25,
    costPerUnit: 24.99,
    lastOrdered: "2024-01-01",
    status: "Critical",
    vendors: [
      { id: 1, name: "Nutrition Plus", price: 24.99, rating: 4.8, deliveryTime: "1-2 days" },
      { id: 2, name: "Protein World", price: 26.5, rating: 4.7, deliveryTime: "2-3 days" },
    ],
  },
  {
    id: 8,
    name: "Frozen Blueberries",
    category: "Fruits",
    currentStock: 18,
    unit: "lbs",
    minStock: 15,
    maxStock: 70,
    costPerUnit: 5.25,
    lastOrdered: "2024-01-06",
    status: "In Stock",
    vendors: [
      { id: 1, name: "Berry Best Farms", price: 5.25, rating: 4.9, deliveryTime: "2-3 days" },
      { id: 2, name: "Wild Berry Co.", price: 5.5, rating: 4.6, deliveryTime: "1-2 days" },
    ],
  },
]; 